---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
cds:
  security:
    mock:
      users:
        - name: admin
          password: admin
          roles:
            - ConfigurationRead
            - ConfigurationCreate
            - ConfigurationUpdate
            - ConfigurationDelete
            - TransactionCreate
            - TransactionRead
            - TransactionUpdate
            - TransactionDelete
            - Posting
            - StockOverviewDisplay
            - MasterDataRead
            - MasterDataCreate
            - MasterDataUpdate
            - MasterDataDelete
            - ExternalPartnerRead
      tenant: my-tenant
server:
  port: 8080